<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Travel Agency - HTML5 Booking template</title>

<!-- Bootstrap -->
<link href="dist/css/bootstrap.css" rel="stylesheet" media="screen">
<link href="assets/css/custom.css" rel="stylesheet" media="screen">

<!-- Animo css-->
<link href="plugins/animo/animate+animo.css" rel="stylesheet" media="screen">

<link href="examples/carousel/carousel.css" rel="stylesheet">
<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
<script src="assets/js/html5shiv.js"></script>
<script src="assets/js/respond.min.js"></script>
<![endif]-->

<!-- Fonts -->	
<link href='http://fonts.googleapis.com/css?family=Lato:400,100,100italic,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Open+Sans:700,400,300,300italic' rel='stylesheet' type='text/css'>	
<!-- Font-Awesome -->
<link rel="stylesheet" type="text/css" href="assets/css/font-awesome.css" media="screen" />
<!--[if lt IE 7]><link rel="stylesheet" type="text/css" href="assets/css/font-awesome-ie7.css" media="screen" /><![endif]-->
<!-- Load jQuery -->
<script src="assets/js/jquery.v2.0.3.js"></script>
</head>
<body>
<script>
function setNewPassword(){
	var newpass = document.getElementById('newPass').value;
	var repass = document.getElementById('repeatPass').value;
	var code = document.getElementById('code').value;
	if(code == ""){
		alert("Enter Autogenerated Code which you got in Email.");
	}else if(newpass == ""){
		alert("Enter New password!");
	}else if(repass == ""){
		alert("Repeat password1");
	}else if(newpass != repass){
		alert("Password should match!");
	}else{
		$.ajax({
			type: 'POST',
			url: 'setNewPassword.php',
			data: {code:code,password:newpass},
			success: function(response) {
				if(response == "success"){
					window.location.href = "user_login.php";
				}else{
					alert(response);
				}
			},
			error: function(error){
				alert(error);
			}
		});
	}
}
</script>
<!-- 100% Width & Height container  -->
<div class="login-fullwidith">
<!-- Login Wrap  -->
<div class="login-wrap">

<img src="images/logo.png" class="login-img" alt="logo"/><br/>
<div class="login-c1" style="height:250px!important;">
<div class="cpadding50">
<input type="text" name="code" id="code" class="form-control logpadding" placeholder="Enter Auto Generated code">
<br/>
<input type="password" name="password" id="newPass" class="form-control logpadding" placeholder="Enter new password">
<br/>
<input type="password" name="resetpassword" id="repeatPass" class="form-control logpadding" placeholder="Repeat new password">
</div>
</div>
<div class="login-c2" style="height:300px !important;">
<div class="logmargfix">
<div class="chpadding50">
<div class="alignbottom">
<button style="width:245px;" class="btn-search4" name="user_login" onclick="setNewPassword();" type="submit" onclick="errorMessage()">Submit</button>							
</div>
</div>
</div>
</div>	
<div class="login-c3" style="margin-top:350px!important;">
<div class="left"><a href="index.php" class="whitelink"><span></span>Website</a></div>
<div class="right"><a href="lost_password.php" class="whitelink">Resend Email</a></div>
</div>		
</div>
<!-- End of Login Wrap  -->

</div>	
<!-- End of Container  -->

<!-- Javascript  -->
<script src="assets/js/initialize-loginpage.js"></script>
<script src="assets/js/jquery.easing.js"></script>
<!-- Load Animo -->
<script src="plugins/animo/animo.js"></script>
<script>
function errorMessage(){
$('.login-wrap').animo( { animation: 'tada' } );
}
</script>

<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="dist/js/bootstrap.min.js"></script>	<script>	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');	  ga('create', 'UA-50123757-1', 'titanicthemes.com');	  ga('send', 'pageview');	</script>	
</body>
</html>